spring:
  application:
    name: alertify-tracking
  datasource:
    url: jdbc:postgresql://localhost:5432/alertify_tracking
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

alertify:
  tracking:
    scan-interval-minutes: 30
    scan-batch-size: 20
    scan-scheduler-rate-ms: 60000
  rabbitmq:
    exchange: scrape.exchange
    routing-key: scrape.key
    completed-queue: scrape.completed.queue