server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

alertify:
  rabbitmq:
    exchange: scrape.exchange
    completed-routing-key: scrape.completed.key
    routing-key: scrape.key
    queue: scrape.queue