server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      type: simple
      simple:
        retry:
          enabled: true
          initial-interval: 2000ms
          multiplier: 2.0
          max-retries: 3
        default-requeue-rejected: false

alertify:
  rabbitmq:
    exchange: scrape.exchange
    completed-routing-key: scrape.completed.key
    routing-key: scrape.key
    queue: scrape.queue